### ISSUE TITLE
Add `raise_for_status()` check to here_api

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#189]
The checking query status piece seems to occasionally return poorly formed json, the function should check the status of the request that before trying to parse the json.

```python
2019-04-09 00:14:32,842 here_api CRITICAL Traceback (most recent call last):
  File "/home/rdumas/git/bdit_data-sources/here/traffic/here_api.py", line 176, in pull_here_data
    download_url = get_download_url(request_id, apis['status_base_url'], access_token, apis['user_id'])
  File "/home/rdumas/git/bdit_data-sources/here/traffic/here_api.py", line 104, in get_download_url
    status = str(query_status.json()['status'])
  File "/home/rdumas/.local/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by radumas** [comment]
Fixed https://github.com/CityofToronto/bdit_data-sources/blob/6d01d093d1696770d87fb6ac584babdf89f1fc90/here/traffic/here_api.py#L51
