### ISSUE TITLE
Miovision API Puller fails with "TypeError: the JSON object must be str, not 'bytes'"

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#222]
Dunno if it also fails not on  airflow. Should also make sure that the return code is non-zero on error.

```python
[2019-09-04 00:00:08,559] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpvdkvas6r/pull_miovisionznqzn6pn
[2019-09-04 00:00:08,560] {bash_operator.py:115} INFO - Running command: /etc/airflow/data_scripts/.venv/bin/python3 /etc/airflow/data_scripts/volumes/miovision/api/intersection_tmc.py run_api --path /etc/airflow/data_scripts/volumes/miovision/api/config.cfg
[2019-09-04 00:00:08,563] {bash_operator.py:124} INFO - Output:
[2019-09-04 00:00:08,996] {bash_operator.py:128} INFO - 04 Sep 2019 00:00:08     	DEBUG    Start
[2019-09-04 00:00:09,032] {bash_operator.py:128} INFO - 04 Sep 2019 00:00:09     	INFO    Pulling from 2019-09-03 00:00:00 to 2019-09-04 00:00:00
[2019-09-04 00:00:09,044] {bash_operator.py:128} INFO - 04 Sep 2019 00:00:09     	DEBUG    Connected to DB
[2019-09-04 00:00:09,057] {bash_operator.py:128} INFO - 04 Sep 2019 00:00:09     	DEBUG    Adelaide / Bathurst     2019-09-03 00:00:00-04:00
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO - 04 Sep 2019 00:00:09     	CRITICAL    Traceback (most recent call last):
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/volumes/miovision/api/intersection_tmc.py", line 243, in pull_data
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -     table=get_intersection_tmc(table, start_date, end_iteration_time, intersection_id1, intersection_uid, key)
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/volumes/miovision/api/intersection_tmc.py", line 163, in get_intersection_tmc
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -     error=json.loads(response.content)
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -   File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO -     s.__class__.__name__))
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO - TypeError: the JSON object must be str, not 'bytes'
[2019-09-04 00:00:09,261] {bash_operator.py:128} INFO - 
[2019-09-04 00:00:09,284] {bash_operator.py:132} INFO - Command exited with return code 0
```

**Comment by radumas** [comment]
So it seems like this may be resolved per https://github.com/CityofToronto/bdit_data-sources/issues/233#issuecomment-553946270

>Should also make sure that the return code is non-zero on error.

@jovenc :point_up: can you change any `sys.exit(0)` calls on error in the script to be `sys.exit(1)`?
