### ISSUE TITLE
Bluetooth email notifications stopped working 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#229]
I think the secrets were expired. Stacktrace from the script:

```python
Traceback (most recent call last):
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'client_secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "brokenreaders.py", line 3, in <module>
    from notify_email import send_mail
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/src/email-notifications/email_notifications/notify_email.py", line 15, in <module>
    CREDENTIALS = get_credentials()
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/src/email-notifications/email_notifications/quickstart.py", line 37, in get_credentials
    flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'client_secret.json', 'No such file or directory', 2)
Traceback (most recent call last):
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'client_secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "notify_routes.py", line 9, in <module>
    from notify_email import send_mail
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/src/email-notifications/email_notifications/notify_email.py", line 15, in <module>
    CREDENTIALS = get_credentials()
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/src/email-notifications/email_notifications/quickstart.py", line 37, in get_credentials
    flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/rdumas/.local/share/virtualenvs/scrapers-ywI8vTu5/lib/python3.5/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'client_secret.json', 'No such file or directory', 2)
```

When I tried to run `pipenv run python -m quickstart` (from [this](https://github.com/CityofToronto/bdit_python_utilities/tree/master/email_notifications#set-up) I get a similar error. Might be a good idea to switch to the service account model? But I can't figure out how to lock down the permissions.

**Comment by radumas** [comment]
I had to use `find . -name "client_secret.json"` to find where I had stashed that file, turns out it wasn't in my copy of the data-sources repo. Once found I `cd` to its location and was able to successfully run `python -m quickstart` from that folder while in my data-sources virtualenv.

guess this will come up again in a year, but hopefully #230 will have been solved by then.
