### ISSUE TITLE
Migrate here_api to run on airflow

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#253]

**Comment by radumas** [comment]
Got an error when trying to export the RDS connection as an environment variable.

```
[2020-01-07 14:51:26,043] {bash_operator.py:124} INFO - Output:
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - Traceback (most recent call last):
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 214, in <module>
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -     main()
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 211, in main
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -     cli(obj={})
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/.venv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -     return self.main(*args, **kwargs)
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/.venv/lib/python3.5/site-packages/click/core.py", line 696, in main
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -     _verify_python3_env()
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/.venv/lib/python3.5/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO -     ' mitigation steps.' + extra
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - 
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - This system supports the C.UTF-8 locale which is recommended.
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - You might be able to resolve your issue by exporting the
[2020-01-07 14:51:26,642] {bash_operator.py:128} INFO - following environment variables:
[2020-01-07 14:51:26,643] {bash_operator.py:128} INFO - 
[2020-01-07 14:51:26,643] {bash_operator.py:128} INFO -     export LC_ALL=C.UTF-8
[2020-01-07 14:51:26,643] {bash_operator.py:128} INFO -     export LANG=C.UTF-8
[2020-01-07 14:51:26,681] {bash_operator.py:132} INFO - Command exited with return code 1
```

So added this to the `'env'` dictionary

```python
'env':{'here_bot':rds_con,
                        'LC_ALL':'C.UTF-8', #Necessary for Click
                        'LANG':'C.UTF-8'}
```
