### ISSUE TITLE
Miovision api script can fail silently

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#330]
There needs to be a `sys.exit(1)` in this exception block so that Airflow will realize that the script has not exited successfully. Right now this block catches any exception and makes it seem like the program ran successfully, which is wrong.

https://github.com/CityofToronto/bdit_data-sources/blob/a22e407b09534dc01da99e15893725c2917f0248/volumes/miovision/api/intersection_tmc.py#L84-L85

For example, log output when changing permission on the `miovision_api` schema meant the script failed early.

```
[2020-09-19 03:00:13,250] {bash_operator.py:124} INFO - Output:
[2020-09-19 03:00:13,526] {bash_operator.py:128} INFO - 72    	INFO    Pulling from 2020-09-18 00:00:00-04:00 to 2020-09-19 00:00:00-04:00
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO - 77    	CRITICAL    Traceback (most recent call last):
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO -   File "/etc/airflow/dev_scripts/volumes/miovision/api/intersection_tmc.py", line 75, in run_api
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO -     pull_data(conn, start_time, end_time, intersection, path, pull, key, dupes)
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO -   File "/etc/airflow/dev_scripts/volumes/miovision/api/intersection_tmc.py", line 287, in pull_data
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO -     cur.execute(string2, (start_time,))
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO - psycopg2.errors.InsufficientPrivilege: permission denied for schema miovision_api
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO - LINE 1: SELECT * FROM miovision_api.intersections
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO -                       ^
[2020-09-19 03:00:13,527] {bash_operator.py:128} INFO - 
[2020-09-19 03:00:13,528] {bash_operator.py:128} INFO - 
[2020-09-19 03:00:13,566] {bash_operator.py:132} INFO - Command exited with return code 0
```

**Comment by cczhu** [comment]
Silly question, do we need to assign `Exception` to `e`? It looks like `traceback` has implicit access due to being in the context manager block.

```
    except Exception as e:
        logger.critical(traceback.format_exc())
        sys.exit(1)
```

**Comment by radumas** [comment]
Ah no we do not, but codefactor gets angry if the except isn't assigned to a variable.

I suspect codefactor was also angry about the blanket exception here. I think the only reason for it was ensuring that the `fileStream` was writing the exception to the log, which is no longer particularly relevant. So instead of writing more code, we could also solve the problem by deleting code.

**Comment by cczhu** [comment]
Oh, interesting that CodeFactor doesn't complain if a variable is assigned as part of a `width` block, but never used.

I don't think it's a big deal either way, was mostly curious about whether writing out `as e` was done deliberately.
