### ISSUE TITLE
Miovision pull fails: "integer out of range"

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#342]
```shell
INFO    Dundas / River     2020-10-11 00:00:00-04:00
[2020-10-12 03:00:45,895] {bash_operator.py:128} INFO - 12 Oct 2020 03:00:45     	INFO    Completed data pulling from s to s
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO - 12 Oct 2020 03:00:45     	ERROR    integer out of range
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO - Traceback (most recent call last):
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/volumes/miovision/api/intersection_tmc.py", line 376, in pull_data
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -     insert_data(conn, c_start_t, c_end_t, table, dupes)
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -   File "/etc/airflow/data_scripts/volumes/miovision/api/intersection_tmc.py", line 281, in insert_data
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -     execute_values(cur, insert_data, table)
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -   File "/home/airflow/.local/lib/python3.5/site-packages/psycopg2/extras.py", line 1281, in execute_values
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO -     cur.execute(b''.join(parts))
[2020-10-12 03:00:45,904] {bash_operator.py:128} INFO - psycopg2.errors.NumericValueOutOfRange: integer out of range
```

My initial thoughts are this is either due to erroneous values in the data or.... the primary key for the series is out of range

**Comment by radumas** [comment]
Not the Primary Key

![image](https://user-images.githubusercontent.com/10623872/95866255-b4a3e600-0d35-11eb-92ba-dbcd2a759646.png)
