### ISSUE TITLE
Modernize WYS Airflow process

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#361]
- [ ] update Slack message
- [ ] make dag pass execution_date

**Comment by radumas** [comment]
Just passing `{{ ds }}` to the dag leads to the following error message

```
ERROR - 'str' object has no attribute 'year'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.5/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/etc/airflow/data_scripts/wys/api/python/wys_api.py", line 286, in api_main
    yr = start_date.year
AttributeError: 'str' object has no attribute 'year'
```
