### ISSUE TITLE
HERE API failing with KeyError: 'accessToken'

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#492]
```
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO - 2022-08-09 21:15:14,403 __main__ CRITICAL Traceback (most recent call last):
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 197, in pull_here_data
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO -     access_token = get_access_token(apis['key_id'], apis['client_secret'], apis['token_url'])
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 50, in get_access_token
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO -     access_token = r.json()['accessToken']
[2022-08-09 21:15:14,404] {bash_operator.py:157} INFO - KeyError: 'accessToken'
```

**Comment by radumas** [comment]
```
2022-08-10 21:27:57,401 __main__ INFO Getting Access Token
2022-08-10 21:27:57,432 __main__ ERROR Error in requesting access token
2022-08-10 21:27:57,432 __main__ ERROR 401 Client Error: Unauthorized for url: https://account.api.here.com/oauth2/token
2022-08-10 21:27:57,432 __main__ CRITICAL Fatal error in pulling data
2022-08-10 21:27:57,432 __main__ CRITICAL Invalid Authorization header, timestamp doesn't match server time.
```

**Comment by radumas** [comment]
This was an issue with the server configuration (guess external NTP is now blocked in our cloud environment).
