### ISSUE TITLE
HERE API fails with KeyError: 'outputUrl'

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#500]
```
2022-08-22 16:40:20,753 __main__ CRITICAL Traceback (most recent call last):
[2022-08-22 16:40:20,753] {bash_operator.py:157} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 201, in pull_here_data
[2022-08-22 16:40:20,753] {bash_operator.py:157} INFO -     download_url = get_download_url(request_id, apis['status_base_url'], access_token, apis['user_id'])
[2022-08-22 16:40:20,753] {bash_operator.py:157} INFO -   File "/etc/airflow/data_scripts/here/traffic/here_api.py", line 120, in get_download_url
[2022-08-22 16:40:20,753] {bash_operator.py:157} INFO -     return query_status.json()['outputUrl']
[2022-08-22 16:40:20,753] {bash_operator.py:157} INFO - KeyError: 'outputUrl'
```

another location where there needs to be a response.raise_for_status() and the block should print the entire response on failure.

**Comment by radumas** [comment]
See pattern from here

https://github.com/CityofToronto/bdit_data-sources/commit/9544caecc823e37b40b33fe0911f13aed164ca3b
