### ISSUE TITLE
`log cleanup` DAG: Deprecated core/base_log_folder in Airflow 2.2.5

### ISSUE THREAD

**Issue by tahaislam** [CityofToronto/bdit_data-sources#529]
After upgrading Airflow to 2.2.5, `base_log_folder` moved to `logging` section in the configuration file. Hence, we're getting the following error:

```
Broken DAG: [/etc/airflow/dags/log_cleanup.py] Traceback (most recent call last):
  File "/home/airflow/airflow_venv/lib/python3.6/site-packages/airflow/configuration.py", line 373, in get
    return self._get_option_from_default_config(section, key, **kwargs)
  File "/home/airflow/airflow_venv/lib/python3.6/site-packages/airflow/configuration.py", line 383, in _get_option_from_default_config
    raise AirflowConfigException(f"section/key [{section}/{key}] not found in config")
airflow.exceptions.AirflowConfigException: section/key [core/base_log_folder] not found in config
```

**Comment by tahaislam** [comment]
> Oh! We got this as a warning before and I just moved the base_log_folder under a new section `logging`, following the config file in morbius

I think they keep changing this from one version to another. It won't break anything also if we added the same field and value to the core
