### ISSUE TITLE
Bug when specifying analysis ids

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#641]
```bash
2023-06-16 14:41:49,826 __main__ INFO Pulling data from 20230601 to 20230615
2023-06-16 14:41:49,826 __main__ INFO Fetching config from blip server
2023-06-16 14:41:50,217 __main__ INFO Fetching info on the following analyses from the database: [1514906, 1515280, 1514986, 1514879, 1514850, 1515251]
2023-06-16 14:41:50,278 __main__ CRITICAL Traceback (most recent call last):
  File "C:\Users\Data_Analytics\blip_api\blip_api.py", line 448, in <module>
    main(**vars(ARGS))
  File "C:\Users\Data_Analytics\blip_api\blip_api.py", line 339, in main
    routes_to_pull = {analysis_id: dict(report_name = report_name) for analysis_id, report_name in cur.fetchone()}
psycopg2.InterfaceError: cursor already closed
```

The following line needs to be tabbed over

https://github.com/CityofToronto/bdit_data-sources/blob/08a4502f59e7f6d4d4bd9d9154dea1fa46e5a7eb/bluetooth/api/blip_api.py#L339

**Comment by chmnata** [comment]
ran into this after tabbing
```
2023-06-19 18:39:06,492 __main__ CRITICAL Traceback (most recent call last):
  File "C:\Users\Data_Analytics\blip_api\blip_api.py", line 448, in <module>
    main(**vars(ARGS))
  File "C:\Users\Data_Analytics\blip_api\blip_api.py", line 339, in main
    routes_to_pull = {analysis_id: dict(report_name = report_name) for analysis_id, report_name in cur.fetchone()}
  File "C:\Users\Data_Analytics\blip_api\blip_api.py", line 339, in <dictcomp>
    routes_to_pull = {analysis_id: dict(report_name = report_name) for analysis_id, report_name in cur.fetchone()}
TypeError: cannot unpack non-iterable int object
```
